spring:
  application:
    name: rabbitmq-producer-multiple-vhost
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: rabbit-advanced
    alternative-host: localhost
    alternative-port: 5672
    alternative-username: admin
    alternative-password: admin
    alternative-virtual-host: /

server:
  port: 9001
